name: Airflow DAG CI/CD

on:
  pull_request:
    branches:
      - master
    paths:
      - 'application/airflow/**'

  push:
    branches:
      - master
    paths:
      - 'application/airflow/**'

permissions:
  contents: write
  id-token: write

jobs:
  # ---------- STEP 1: PR Scan ----------
  pr_security_scan:
    if: github.event_name == 'pull_request'
    name: PR Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint the flakes
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  # ---------- STEP 2: Post-Merge Sonar Scan ----------
  post_merge_security_scan:
    if: github.event_name == 'push'
    name: Post-Merge SonarQube Scan
    runs-on: ubuntu-latest
    outputs:
      scan_result: ${{ steps.scan.outcome }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate check
        id: quality_check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: Fail if Quality Gate fails
        if: steps.quality_check.outcome != 'success'
        run: exit 1

  # ---------- STEP 3: Tag, Release, Upload to JFrog ----------
  release_and_publish:
    if: github.event_name == 'push'
    name: Create Release & Upload Artifact
    needs: post_merge_security_scan
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Version
        id: set_version
        run: |
          VERSION="v1.0.${{ github.run_number }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create ZIP Artifact
        run: |
          mkdir -p build
          zip -r build/dag-${{ env.VERSION }}.zip application/airflow/

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a ${{ env.VERSION }} -m "Release ${{ env.VERSION }}"
          git push origin ${{ env.VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: |
            DAG artifact version `${{ env.VERSION }}` created and uploaded to JFrog.

      - name: Upload ZIP to JFrog
        run: |
          curl -u ${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_PASSWORD }} \
            -T build/dag-${{ env.VERSION }}.zip \
            "https://your-jfrog-instance.jfrog.io/artifactory/your-repo/dag-${{ env.VERSION }}.zip"

  # ---------- STEP 4: Manual Approval ----------
  manual_approval:
    if: github.event_name == 'push'
    name: Manual Approval
    needs: release_and_publish
    runs-on: ubuntu-latest
    environment:
      name: uat
      url: https://console.cloud.google.com/storage/browser/test-backend-123/terraform/dags
    steps:
      - name: Wait for Approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: jyotibhagat1
          minimum-approvals: 1
          issue-title: "Approve Airflow DAG Release"
          issue-body: "Version ${{ needs.release_and_publish.outputs.release_version }} is ready for UAT deployment."
          secret: ${{ secrets.GITHUB_TOKEN }}

  # ---------- STEP 5: Deploy to GCS from JFrog ----------
  deploy:
    if: github.event_name == 'push'
    name: Deploy DAGs to GCS - UAT
    needs: [release_and_publish, manual_approval]
    runs-on: ubuntu-latest
    steps:
      - name: Download from JFrog
        run: |
          curl -u ${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_PASSWORD }} \
            -O "https://your-jfrog-instance.jfrog.io/artifactory/your-repo/dag-${{ needs.release_and_publish.outputs.release_version }}.zip"

      - name: Unzip Artifact
        run: |
          unzip dag-${{ needs.release_and_publish.outputs.release_version }}.zip -d dags/

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Backup Current DAGs
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          gsutil -m cp -r gs://test-backend-123/terraform/dags gs://test-backend-123/terraform/backups/dags-$TIMESTAMP

      - name: Upload to GCS
        run: |
          gsutil -m rsync -r -c dags/application/airflow/ gs://test-backend-123/terraform/dags

  # ---------- STEP 6: Rollback on Failure ----------
  rollback:
    if: github.event_name == 'push' && failure()
    name: Rollback DAGs from Backup
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Rollback DAGs
        run: |
          echo "Rolling back DAGs..."
          # Replace this with actual backup timestamp if needed
          gsutil -m cp -r gs://test-backend-123/terraform/backups/latest/* gs://test-backend-123/terraform/dags/
