name: Airflow DAG Deployment - UAT

on:
  pull_request:
    branches:
      - master
    paths:
      - 'application/cloudrun/folder2/**'

  push:
    branches:
      - master
    paths:
      - 'application/cloudrun/folder2/**'

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

# --------- STEP 1: PR Checks (Security Scan only) ---------
jobs:
  pr_security_scan:
    # if: github.event_name == 'pull_request'
    name: PR Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
         ref: master  # ✅ Specific branch
         sparse-checkout: |
             application/cloudrun/folder2/
         sparse-checkout-cone-mode: false
         fetch-depth: 1

      - name: Run Bandit Scan
        run: |
          ls -l application/
