name: List services in GCP
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/645536778937/locations/global/workloadIdentityPools/githubactions/providers/github-actions'
          service_account: 'github-actions@vast-silicon-456014-j2.iam.gserviceaccount.com'

      - id: 'gcloud'
        name: 'gcloud'
        run: |-
             gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
             gcloud services list
